### ISSUE TITLE
fedmsg is ending, port to fedora-messaging

### ISSUE THREAD

**Issue by praiskup** [release-engineering/dist-git#29]
SSIA, per https://communityblog.fedoraproject.org/moving-from-fedmsg-to-fedora-messaging/

I'm not sure what we use fedmsg for, I've just seen we depend on it:
https://bugzilla.redhat.com/show_bug.cgi?id=1814463

**Comment by clime** [comment]
I think we could support both...

**Comment by xsuchy** [comment]
FYI https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/LMGG3J5QKN2E3IOF4JZAKVQVRZ2A6VZW/
It seems that the publishing of messages is still preferred.

IMO it does not have the sense to support both. I suggest moving from fedmsg to fedora-messaging.

**Comment by clime** [comment]
@xsuchy Hello and thank you for the investigation! I would like to keep the support for fedmsg for backward compatibility and because I think fedmsg might still have some potential as a distribution-independent messaging bus. 

A big trial will be whether fedmsg can get to epel8 https://bugzilla.redhat.com/show_bug.cgi?id=1815695

**Comment by praiskup** [comment]
The "fedmsg" is mostly instance of zmq bus. The python code is pre-configurated wrapper
around zmq.  The message bus is going to be shut-down.  Please elaborate on what do
you plan to keep compatibility with when there will be no fedmsg bus.

**Comment by clime** [comment]
@praiskup Sure, I don't see dist-git as something Fedora-specific but rather a tool that any distro can use so I would like to keep fedmsg support, which was a distribution independent message bus.

**Comment by praiskup** [comment]
Anyone else than Fedora runs fedmsg bus?  Fedmsg isn't distro independent, same as fedora-messaging isn't, or?

**Comment by praiskup** [comment]
I mean, I reported this some time ago https://github.com/fedora-infra/fedora-messaging/issues/195
except that fedora-messaging has "fedora" in name, in principle it isn't less distro-agnostic
chan fedmsg.

**Comment by clime** [comment]
Debian used to run fedmsg bus but they dropped it because mainly it wasn't reliable enough for them. I think this could be fixed. 

fedmsg aimed to be distro independendant. It's name was changed from “Fedora Messaging”  to  “Federated Message Bus” (per http://fedmsg.com/federated-message-bus/). Also fedmsg has a big history

... yes right, you just wrote it.

There was also some good design planning for fedmsg initially (http://fedmsg.com/en/latest/overview/) - so I think the fedmsg might still be a good tool.

**Comment by praiskup** [comment]
> it wasn't reliable enough for them. I think this could be fixed.

Not sanely.  Because 0mq.  Maybe by porting to different relay method
(but then you want to use fedora-messaging).  I view compat attempts as
complete waste of energy (as long as you say full story :-)).

**Comment by clime** [comment]
To tell the truth, I am still investigating the messaging topic. I like the default decentralized nature zeromq and I am e.g. thinking that an sqlite persistence could be added to 0mq producers to handle temporary remote service unavailability. At the moment I don't see into the problematic sufficiently well to know whether this is viable or not but I think there will be options to provide sufficient reliability to fedmsg. To me, it makes sense to explore these options and I think it is too soon to ditch fedmsg now, especially if it can get to epel8. The question also is what reliability is really expected (i.e. no message can never be lost vs. temporary service drops are ok vs. you are able to consume message now or it is thrown away) - that's also something I would like to find out.

Reading the bug you posted, fedora-messaging really seems to be Fedora-focused which is _fine_ but it's not what the dist-git project is about, I think.

**Comment by praiskup** [comment]
On Tuesday, March 24, 2020 3:21:06 PM CET Michal Novotný wrote:
> Reading the bug you posted, fedora-messaging really seems to be Fedora-focused
> which is _fine_ but it's not what the dist-git project is about, I think.

Ok, NP with me, I think the fedmsg code can exist in dist-git as opt-in, as long
as it zero maintenance cost for us.  That is -> it won't be tested, and
maintained by us.  It shall not block installation even if fedmsg isn't
available.

As I claimed elsewhere;  we'll have to probably port dist-git to
fedora-messaging anyway (according to @xsuchy point above, it is desired).  And
the only viable option is to drop fedmsg, and introduce fedora-messaging.  So if
you want to keep fedmsg support opt-in - please be fast and make it fully
optional (on runtime and installation level).  I mean, once we are on it -
we'll just drop the fedmsg support because there are no customers.

**Comment by pypingou** [comment]
> Reading the bug you posted, fedora-messaging really seems to be Fedora-focused which is fine but it's not what the dist-git project is about, I think.

Like fedmsg is an overlay over zeromq, fedora-messaging is an overlay over amqp. There is very little that is fedora-specific in fedora-messaging

**Comment by clime** [comment]
> > Reading the bug you posted, fedora-messaging really seems to be Fedora-focused which is fine but it's not what the dist-git project is about, I think.
> 
> Like fedmsg is an overlay over zeromq, fedora-messaging is an overlay over amqp. There is very little that is fedora-specific in fedora-messaging

Ok, but it's also about the author intention. If there is enough drive to keep things generic enough so that they can be easily scaled and reused even beyond Fedora boundary, then fine, i then think the name you picked doesn't carry that intention over very well. Another thing is what technology is the most suitable one to provide a distribution-generic messaging bus. You are currently saying amqp+rabbitmq - it might be true but I would like to check it or let time decide.

**Comment by clime** [comment]
Addressed in https://github.com/release-engineering/dist-git/pull/36.
