### ISSUE TITLE
systemd dependency

### ISSUE THREAD

**Issue by cz172638** [release-engineering/dist-git#3]
hi,
since 0.3 it is not 'packagable' for rhel6.
i would like to see support for rhel6/centos6.

best regards
j.

**Comment by xsuchy** [comment]
Why? SysVinit is step back. We have RHEL7 and all Fedoras.

**Comment by cz172638** [comment]
lot of production systems are running on rhel6/centos6 and you know it: 'if it works, don't touch it'.

**Comment by xsuchy** [comment]
Nope. All Fedora infrastructure systems are either running on EL7 or Fedora20+.

**Comment by cz172638** [comment]
i mean rest of the world

**Comment by asamalik** [comment]
At the moment we are targeting the Fedora Infrastructure systems. As Mirek said, they are all running platforms with systemd. At first, I would like to make this project ready and have it running in the Fedora Infrastructure as a replacement for the current solution.

Your point would be relevant to new deployments. But I'm not sure if I want to support any new deployments on EL6 or even older platforms. I agree with you that it would be nice to support more systems. However, I would also like to keep this project as simple as possible and focus on new features and enhancements rather than supporting old systems.

**Comment by clime** [comment]
I agree with asamalik here. But we probably could make it EPEL6 compatible. Please, send us PR with the required changes or reopen this (old) issue if you still care about this.
